Repository codestates-seb/seb45_main_030, pull requests merged in 2023-09, with the labels that each got.

#29 [BE] ✨ UserResponseDto 데이터 필드 추가, UserService 이미 존재하는 유저 예외처리 추가, 존재하지 않는 유저에 대한 예외처리 추가, UserController 유저 정보 받아오는 메서드 추가
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/controller/UserController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserLogoutDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/repository/UserRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/service/AuthUserDetailsService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/service/UserService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/utils/UserAuthorityUtils.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/config/SecurityConfiguration.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/JwtTokenizer.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/filter/JwtAuthenticationFilter.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/filter/JwtExceptionFilter.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/filter/JwtVerificationFilter.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/handler/UserAccessDeniedHandler.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/handler/UserAuthenticationEntryPoint.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/handler/UserAuthenticationFailureHandler.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/handler/UserAuthenticationSuccessHandler.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/BusinessLogicException.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/ExceptionCode.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/advice/GlobalExceptionAdvice.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/response/ErrorResponder.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/response/ErrorResponse.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/redis/util/RedisUtil.java
Labels: Back, 기능추가, 리펙토링, 수정

#34 [BE] ✨ USER 서비스, 컨트롤러 CRUD 추가
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/controller/UserController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserPatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserProfileImageDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/mapper/UserMapper.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/service/UserService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/image/controller/AmazonS3Controller.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/image/service/AwsS3Service.java
Labels: Back, 기능추가, 리펙토링, 수정

#41 [BE] 🎉 Bookmark 매퍼, 서비스, 리포지토리, 컨트롤러 추가
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/controller/BookmarkController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/dto/BookmarkPostDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/dto/BookmarkResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/entity/Bookmark.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/mapper/BookmarkMapper.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/repository/BookmarkRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/service/BookmarkService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/entity/Post.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/controller/UserController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserResponseSimpleDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/entity/Users.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/mapper/UserMapper.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/config/SecurityConfiguration.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/filter/JwtVerificationFilter.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/ExceptionCode.java
Labels: Back, 기능추가, 버그

#42 [BE] 게시글 기능 추가
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/dto/BookmarkPostDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/entity/Bookmark.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/mapper/BookmarkMapper.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/service/BookmarkService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/comment/entity/Comment.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/controller/PostsController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostPatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostPostDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostsPatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostsPostDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostsResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/entity/Post.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/entity/Posts.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/mapper/PostsMapper.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/repository/PostsRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/service/PostsService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/postTag/entity/PostTag.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommendPost/entity/RecommendPost.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/tag/entity/Tag.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/tag/repository/TagRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/controller/UserController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserResponseSimpleDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/entity/Users.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/repository/UserRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/service/UserService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/ExceptionCode.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/response/MultiResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/response/PageInfo.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/image/AwsS3Service.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/image/S3Config.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/image/config/S3Config.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/image/controller/AmazonS3Controller.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/image/service/AwsS3Service.java
  server/grilledshrimp/src/main/resources/application.yml
Labels: Back, 기능추가, 수정

#45 ✨ [BE] Bookmark, JWT 수정
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/controller/BookmarkController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/dto/BookmarkDeleteDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/mapper/BookmarkMapper.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/repository/BookmarkRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/service/BookmarkService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/controller/PostsController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/controller/UserController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserNamePatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserPasswordPatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserPatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserProfileImageDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/entity/Users.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/service/UserService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/config/SecurityConfiguration.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/filter/JwtAuthenticationFilter.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/filter/JwtVerificationFilter.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/jwt/handler/UserAuthenticationFailureHandler.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/ExceptionCode.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/response/ErrorResponder.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/response/ErrorResponse.java
  server/grilledshrimp/src/main/resources/application.yml
Labels: Back, 기능추가, 수정

#50 [BE] 게시글, 추천 그외 등등 추가
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/bookmark/entity/Bookmark.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/comment/dto/CommentDTO.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/comment/dto/CommentPatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/comment/dto/CommentPostDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/comment/dto/CommentResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/comment/entity/Comment.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/comment/repository/CommentRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/controller/PostsController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostsPatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostsPostDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostsResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/dto/PostsResponseSimpleDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/entity/Posts.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/mapper/PostsMapper.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/repository/PostsRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/post/service/PostsService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/postTag/entity/PostTag.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommend/controller/RecommendController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommend/dto/RecommendPostDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommend/dto/RecommendResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommend/entity/Recommend.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommend/repository/RecommendRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommend/service/RecommendService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommendComment/dto/RecommendCommentPatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommendComment/dto/RecommendCommentResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommendComment/entity/RecommendComment.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommendPost/dto/RecommendPostPatchDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/recommendPost/dto/RecommendPostResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/tag/dto/TagResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/controller/UserController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/entity/Users.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/repository/UserRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/service/UserService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/ExceptionCode.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/response/MultiResponseDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/exception/response/PageInfo.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/image/AwsS3Service.java
Labels: Back, 기능추가, 리펙토링, 수정

#51 ✨ [BE] 유저 이메일 찾기, 유저 비밀번호 변경 기능 추가
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/controller/UserController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserCheckDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserFindEmailByUserNameDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/dto/UserUpdatePasswordDto.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/repository/UserRepository.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/service/UserService.java
Labels: Back, 기능추가

#35 게시글입력화면 생성
  client/package-lock.json
  client/package.json
  client/src/components/Comment/CommentComponent.jsx
  client/src/components/Comment/CommentComponent.module.css
  client/src/components/PostData.jsx
  client/src/components/PostDetail/PostDetail.jsx
  client/src/components/PostDetail/PostDetail.module.css
  client/src/components/PostDetail/PostModal.jsx
  client/src/components/UploadModal/Modal.jsx
  client/src/components/UploadModal/UploadForm.jsx
  client/src/components/UploadModal/UploadForm.module.css
  client/src/pages/App.jsx
  client/src/recoil/atom.js
Labels: Front, 기능추가

#26 [FE] 메인페이지 & 무한 스크롤 컴포넌트
  client/.gitignore
  client/src/assets/icon/bookmark.svg
  client/src/assets/icon/personpin.svg
  client/src/assets/icon/thumbup.svg
  client/src/assets/image/banner.png
  client/src/components/Image/ImageItem.jsx
  client/src/components/Image/ImageItem.module.css
  client/src/components/Image/ImageList.jsx
  client/src/components/Image/ImageList.module.css
  client/src/components/button/Button.module.css
  client/src/components/button/ButtonBookmark.jsx
  client/src/components/button/ButtonRecommend.jsx
  client/src/hooks/useInfiniteGetImage.jsx
  client/src/pages/App.jsx
  client/src/pages/App.module.css
  client/src/pages/MainPage.jsx
  client/src/pages/MainPage.module.css
Labels: Front, 기능추가

#54 [FE] 메이페이지 API 통신 적용
  client/src/components/Image/ImageItem.jsx
  client/src/components/Image/ImageList.jsx
  client/src/components/PostDetail/PostModal.jsx
  client/src/components/button/ButtonBookmark.jsx
  client/src/components/button/ButtonRecommend.jsx
  client/src/hooks/useInfiniteGetImage.jsx
  client/src/pages/MainPage.jsx
Labels: Front, 기능추가

#55 [BE] 기능 추가 및 수정
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/comment/controller/CommentController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/comment/service/CommentService.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/search/controller/SearchController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/entity/Users.java
Labels: Back, 기능추가, 리펙토링, 수정

#58 [BE] 코드 수정
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/domain/user/controller/UserController.java
  server/grilledshrimp/src/main/java/com/mainproject/grilledshrimp/global/auth/config/SecurityConfiguration.java
Labels: Back, 버그, 수정

#57 [FE] 헤더 컴포넌트
  client/src/components/Common/Header.jsx
  client/src/components/Common/Header.module.css
  client/src/components/Image/ImageItem.module.css
  client/src/components/UploadModal/Modal.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/MainPage.module.css
  client/src/pages/SignupPage.css
Labels: Front, 레이아웃
